### ISSUE TITLE
Adding a new "PATH" field to the template for Dockerfile and Docker Compose

### ISSUE THREAD

**Issue by ceylanb** [HappyHackingSpace/vulnerable-target#26]
It would be nice to have an additional optional `path` field for `docker` and `docker_compose` as follows.
```
  docker:
    ports:  # add ports for container
      "hostPort/protocol": "containerPort"
    content: # (Optional) 
    path: /dockerfile/path (Optional)
  docker_compose:
    content: (Optinal)
    path: /docker-compose.yml/path (Optional)
```
